### ISSUE TITLE
'No service matches hana'

### ISSUE THREAD

**Issue by harun** [SAP-samples/hana-developer-cli-tool-example#1]
when try to command *hana-cli cds init bookshop -add hana*

I got the following error :

```javascript
VError: No service matches hana
    at Object.getServices (C:\Driver\code\hana\hana-developer-cli-tool-example\node_modules\@sap\xsenv\lib\xsservices.js:50:15)
    at C:\Driver\code\hana\hana-developer-cli-tool-example\utils\dbPromises.js:13:21
    at new Promise (<anonymous>)
    at Function.createConnectionFromEnv (C:\Driver\code\hana\hana-developer-cli-tool-example\utils\dbPromises.js:8:10)
    at cds (C:\Driver\code\hana\hana-developer-cli-tool-example\bin\cds.js:86:40)
    at C:\Driver\code\hana\hana-developer-cli-tool-example\bin\cds.js:80:5
    at C:\Driver\code\hana\hana-developer-cli-tool-example\node_modules\prompt\lib\prompt.js:336:32
    at C:\Driver\code\hana\hana-developer-cli-tool-example\node_modules\async\lib\async.js:154:25
    at assembler (C:\Driver\code\hana\hana-developer-cli-tool-example\node_modules\prompt\lib\prompt.js:333:9)
    at C:\Driver\code\hana\hana-developer-cli-tool-example\node_modules\prompt\lib\prompt.js:342:32 {
  jse_shortmsg: 'No service matches hana',
  jse_info: {},
  message: 'No service matches hana'
\
/
Error: Invalid Input Table
    at Object.getTable (C:\Driver\code\hana\hana-developer-cli-tool-example\utils\dbInspect.js:59:9)


```

**Comment by jung-thomas** [comment]
I think there is some misunderstand about what the han-cli cds command does.  https://github.com/SAP-samples/hana-developer-cli-tool-example#cds

It does not expose the cds tool directly as you are trying to use it.  It uses CDS internally to dynamically generate an OData service for an existing table/view in your HANA system.

Furthermore the error you are receiving is normal if you've not logged into the HANA system yet via the hana-cli connect command. https://github.com/SAP-samples/hana-developer-cli-tool-example#connect
This command will create the default-env.json file that contains the connection parameters.

**Comment by luizcarlospedrosogomes** [comment]
Or  use https://www.npmjs.com/package/@sap/xsenv#local-environment-setup 
>>>>> default-env.json

add to .gitignore this file
