### ISSUE TITLE
not able to execute commands in HANA 1.0 sps12 - VError: No service matches hana

### ISSUE THREAD

**Issue by sucheno** [SAP-samples/hana-developer-cli-tool-example#11]
Hi Team, I have connected hana-cli to hana 1.0 sps 12. I was intending to use massConvert to convert all table in a schema to .hdbtable files.

But I am not able to execute any commands as the below error is thrown.

`{ VError: No service matches hana
    at Object.getServices (C:\Users\<username>\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\node_modules\@sap\xsenv\lib\xsservices.js:50:15)
    at Promise (C:\Users\<username>\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\node_modules\sap-hdbext-promisfied\index.js:15:33)
    at new Promise (<anonymous>)
    at Function.createConnectionFromEnv (C:\Users\<username>\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\node_modules\sap-hdbext-promisfied\index.js:9:16)
    at dbStatus (C:\Users\<username>\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\bin\status.js:49:48)
    at prompt.get (C:\Users\<username>\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\bin\status.js:43:10)
    at C:\Users\<username>\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\node_modules\prompt\lib\prompt.js:336:32
    at C:\Users\<username>\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\node_modules\utile\node_modules\async\lib\async.js:154:25
    at assembler (C:\Users\<username>\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\node_modules\prompt\lib\prompt.js:333:9)
    at C:\Users\<username>\Documents\Suchen Workspaces\vscode files\hana-developer-cli-tool-example\node_modules\prompt\lib\prompt.js:342:32
  jse_shortmsg: 'No service matches hana',
  jse_info: {},`

**Comment by jung-thomas** [comment]
In the folder in which you are using the hana-cli do you have a default-env.json or a default-env-admin.json?  This error would indicate it can't either find you default-env.json file or it is missing a hana section. This file contains the connection parameters to login to your HANA system. If you are using a default-env-admin.json, then remember to add the -a (to denote the use of an Admin connection) to most commands.

**Comment by sucheno** [comment]
Thanks @jung-thomas .
I have default-env-admin.json, Commands are working now with admin option.
Closing the issue.
